### ISSUE TITLE
Scrum Update #2 - June 6, 2020

### ISSUE THREAD

**Issue by jenessatan** [Cainuse/tradeforce-client#10]
1. What did you work on this past iteration (2 weeks)?

3. What were any major issues/challenges you ran into?
 
5. What do you plan to work on for this coming iteration?

**Comment by jenessatan** [comment]
s9p1b
1. I created the [wireframe](https://www.figma.com/file/SxZ9wbue3i3hN9i6QkNf3z/Tradeforce?node-id=0%3A1) for the application UI. I completed the Items details page consisting of the Item Details component and the Reviews components.

**Comment by Cainuse** [comment]
i8v0b
1. What did you work on this past iteration (2 weeks)?
- Built search bar and item category card components
- Reasearched React hooks
- Attempted to set up CD (currently blocked)

2. What were any major issues/challenges you ran into?
- Heroku CLI issue

3. What do you plan to work on for this coming iteration?
- Landing page with search bar and category cards displayed with valid data
- Set up NodeJS server 
- (Attempt to: Low priority) Set up CD

**Comment by jenessatan** [comment]
s9p1b
1. I created the [wireframe](https://www.figma.com/file/SxZ9wbue3i3hN9i6QkNf3z/Tradeforce?node-id=0%3A1) for the application UI. I completed the Items details page consisting of the Item Details component and the Reviews components.

2. Learning Figma and designing the application; familiarizing myself with MaterialUI

3. Add New Post component with associated Redux

**Comment by abid-salahi** [comment]
z2u0b

1. Created item posting preview component and set up react router

2. Setting up the material ui grid and using css to dynamically style the page

3. Refactor react router to be dynamic and work with specific item postings, as well as integrate reviews with user and potentially set up user profile for reviews to be attached to (lower priority currently).

**Comment by jacquelineyin** [comment]
r6s1b

1. Created Navigation Bar component, researched material ui and set up the theme & styled

2. Learning Redux & learning Material UI. (Material UI's documentation is confusion at first)

3. Styling & adding ability to create an offering (through redux) to an already existing posting
