### ISSUE TITLE
Scrum Update #1 - May 23, 2020

### ISSUE THREAD

**Issue by jacquelineyin** [Cainuse/tradeforce-client#2]
1. What did you work on this past iteration (2 weeks)?

2. What were any major issues/challenges you ran into?

3. What do you plan to work on for this coming iteration?

**Comment by jacquelineyin** [comment]
r6s1b

1. What did you work on this past iteration (2 weeks)?
         - Basic design/prototype of landing page and browsing page
         - Updated README with first project Task

2. What were any major issues/challenges you ran into?
        - Figma doesn't allow for more than 2 editors at once for free 
        - Deciding on a project idea was more difficult partly due to the online-ness of everything

3. What do you plan to work on for this coming iteration?
        - **Navigation Bar Component**
        - More concrete wireframing
        - Designing the architecture of the project?
        - A more concrete plan for components that will be needed? 
        - Research MongoDB?

**Comment by jenessatan** [comment]
s9p1b

1. collaborated on the basic design/prototype of the application, outlined our project requirements and completed project proposal

2. main challenge was the limitations of collaborating virtually

3. creating a more concrete wireframe of our application to work from and creating the post preview components for the item search results pages

**Comment by abid-salahi** [comment]
z2u0b

1. What did you work on this past iteration (2 weeks)?
- Design of the application prototype which includes front page and search bar and navar
- Committed application prototype
- Worked through setting up basic and standard project requirements

2. What were any major issues/challenges you ran into?
- Figma editting issues and challenges
- Project topic confirmation

3. What do you plan to work on for this coming iteration?
- Create Item posting component with its corresponding sub components

**Comment by Cainuse** [comment]
i8v0b
1. What did you work on this past iteration (2 weeks)?
    - Contributed to UI design
    - Fleshed out project idea and contributed to project documentation
    - GitHub Repo Management
2. What were any major issues/challenges you ran into?
    - Figma Free Tier limitations
    - DIfference in problem statement for project
3. What do you plan to work on for this coming iteration?
    - Set up project for CD
    - Build Search Bar and Categories box components
    - Research Material-UI library
